export default {
  patient: {
    type: 'object',
    required: ['firstname', 'lastname', 'birthdate', 'social_security_number', 'phone_number', 'email', 'address'],
    properties: {
      id: { type: 'integer', description: 'The auto-generated id for the patient.' },
      firstname: { type: 'string', description: "Patient's firstname." },
      lastname: { type: 'string', description: "Patient's lastname." },
      birthdate: { type: 'string', description: "Patient's birthdate." },
      socialSecurityNumber: { type: 'string', description: "Patient's social_security_number." },
      phoneNumber: { type: 'string', description: "Patient's phone number." },
      email: { type: 'string', description: "Patient's email." },
      address: { type: 'string', description: "Patient's address." },
      zipCodeId: { type: 'integer', description: "Patient's zip code id." },
      createdAt: {
        type: 'string',
        format: 'date-time',
        description: 'Date of creation.',
      },
      updatedAt: {
        type: 'string',
        format: 'date-time',
        description: 'Date of last update.',
      },
    },
    example: {
      id: 2,
      firstname: 'Jane',
      lastname: 'Doe',
      birthdate: '01/01/1900',
      socialSecurityNumber: '123456789',
      phoneNumber: '0601020304',
      email: 'jane@doe.com',
      address: '5 rue de la paix',
      zipCodeId: 2,
      createdAt: '2024-03-10 09:43:05.757',
      updatedAt: '2024-03-10',
    },
  },
};
