export default {
  patientsListWithLastMessage: {
    type: 'object',
    additionalProperties: {
      type: 'object',
      required: ['firstname', 'lastname', 'birthdate', 'socialSecurityNumber', 'phoneNumber', 'email', 'address'],
      properties: {
        id: { type: 'integer', description: 'The auto-generated id for the patient.' },
        zipCodeId: { type: 'integer', description: 'The zip code id for the patient.' },
        firstname: { type: 'string', description: "Patient's firstname." },
        lastname: { type: 'string', description: "Patient's lastname." },
        birthdate: { type: 'string', format: 'date-time', description: "Patient's birthdate." },
        socialSecurityNumber: { type: 'string', description: "Patient's social security number." },
        phoneNumber: { type: 'string', description: "Patient's phone number." },
        email: { type: 'string', description: "Patient's email." },
        address: { type: 'string', description: "Patient's address." },
        createdAt: {
          type: 'string',
          format: 'date-time',
          description: 'Date of creation.',
        },
        updatedAt: {
          type: 'string',
          format: 'date-time',
          description: 'Date of last update.',
        },
        channels: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: { type: 'integer', description: 'The auto-generated id for the channel.' },
              patientId: { type: 'integer', description: 'The id of the patient associated with the channel.' },
              channelTypeId: { type: 'integer', description: 'The id of the channel type.' },
            },
          },
        },
        lastMessage: {
          type: 'object',
          properties: {
            id: { type: 'string', description: 'The auto-generated id for the last message.' },
            channelId: { type: 'integer', description: 'The id of the channel associated with the last message.' },
            content: { type: 'string', description: 'The content of the last message.' },
            authorId: { type: 'integer', description: 'The id of the author of the last message.' },
            timestamp: { type: 'string', format: 'date-time', description: 'The timestamp of the last message.' },
          },
        },
        unreadMessagesCount: { type: 'integer', description: 'The number of unread messages for the patient.' },
      },
    },
    example: {
      1: {
        id: 1,
        zipCodeId: 691,
        firstname: 'Capitaine',
        lastname: 'Haddock',
        birthdate: '1980-01-01T00:00:00.000Z',
        socialSecurityNumber: '123456789012345',
        phoneNumber: '0123456789',
        email: 'capitaine@haddock.fr',
        address: '123 rue du port',
        createdAt: '2024-04-09T09:28:59.954Z',
        updatedAt: '2024-04-09T09:28:59.954Z',
        channels: [
          { id: 1, patientId: 1, channelTypeId: 1 },
          { id: 2, patientId: 1, channelTypeId: 2 },
          { id: 3, patientId: 1, channelTypeId: 3 },
          { id: 4, patientId: 1, channelTypeId: 4 },
        ],
        lastMessage: {
          id: '6617eeb67b8bfa2f0e92cfbd',
          channelId: 4,
          content: 'Un test famille capitaine',
          authorId: 1,
          timestamp: '2024-04-15T13:32:24.000Z',
        },
        unreadMessagesCount: 6,
      },
      2: {
        id: 2,
        zipCodeId: 4529,
        firstname: 'Tintin',
        lastname: 'Reporter',
        birthdate: '1985-01-01T00:00:00.000Z',
        socialSecurityNumber: '987654321012345',
        phoneNumber: '9876543210',
        email: 'tintin@reporter.fr',
        address: '456 boulevard de Moulinsart',
        createdAt: '2024-04-09T09:28:59.963Z',
        updatedAt: '2024-04-09T09:28:59.963Z',
        channels: [
          { id: 5, patientId: 2, channelTypeId: 1 },
          { id: 6, patientId: 2, channelTypeId: 2 },
          { id: 7, patientId: 2, channelTypeId: 3 },
        ],
        lastMessage: {
          id: '6617eee97b8bfa2f0e92cfc3',
          channelId: 7,
          content: 'Tintin en service radiologie',
          authorId: 1,
          timestamp: '2024-04-15T13:32:24.000Z',
        },
        unreadMessagesCount: 0,
      },
    },
  },
};
