export default {
  patientWithUsers: {
    type: 'object',
    required: ['firstname', 'lastname', 'birthdate', 'socialSecurityNumber', 'phoneNumber', 'email', 'address'],
    properties: {
      id: { type: 'integer', description: 'The auto-generated id for the patient.' },
      zipCodeId: { type: 'integer', description: 'The zip code id for the patient.' },
      firstname: { type: 'string', description: "Patient's firstname." },
      lastname: { type: 'string', description: "Patient's lastname." },
      birthdate: { type: 'string', format: 'date-time', description: "Patient's birthdate." },
      socialSecurityNumber: { type: 'string', description: "Patient's social security number." },
      phoneNumber: { type: 'string', description: "Patient's phone number." },
      email: { type: 'string', description: "Patient's email." },
      address: { type: 'string', description: "Patient's address." },
      createdAt: {
        type: 'string',
        format: 'date-time',
        description: 'Date of creation.',
      },
      updatedAt: {
        type: 'string',
        format: 'date-time',
        description: 'Date of last update.',
      },
      users: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'integer', description: 'The auto-generated id for the user.' },
            firstname: { type: 'string', description: "User's firstname." },
            lastname: { type: 'string', description: "User's lastname." },
            email: { type: 'string', description: "User's email." },
            rppsCode: { type: 'string', description: "User's RPPS code." },
            profilePictureUrl: { type: 'string', description: "User's profile picture URL." },
            createdAt: {
              type: 'string',
              format: 'date-time',
              description: 'Date of creation.',
            },
            updatedAt: {
              type: 'string',
              format: 'date-time',
              description: 'Date of last update.',
            },
          },
        },
      },
    },
    example: {
      id: 1,
      zipCodeId: 691,
      firstname: 'Capitaine',
      lastname: 'Haddock',
      birthdate: '1980-01-01T00:00:00.000Z',
      socialSecurityNumber: '123456789012345',
      phoneNumber: '0123456789',
      email: 'capitaine@haddock.fr',
      address: '123 rue du port',
      createdAt: '2024-04-09T09:28:59.954Z',
      updatedAt: '2024-04-09T09:28:59.954Z',
      users: [
        {
          id: 1,
          firstname: 'Alice',
          lastname: 'Smith',
          email: 'alice@smith.com',
          rppsCode: '12345678901',
          profilePictureUrl: 'https://example.com/image1.jpg',
          createdAt: '2024-04-09T09:28:59.605Z',
          updatedAt: '2024-04-09T09:28:59.605Z',
        },
        {
          id: 2,
          firstname: 'Bob',
          lastname: 'Brown',
          email: 'bob@brown.com',
          rppsCode: '12345678902',
          profilePictureUrl: 'https://example.com/image2.jpg',
          createdAt: '2024-04-09T09:28:59.695Z',
          updatedAt: '2024-04-09T09:28:59.695Z',
        },
      ],
    },
  },
};
