export default {
  patientWithChannels: {
    type: 'object',
    required: ['firstname', 'lastname', 'birthdate', 'socialSecurityNumber', 'phoneNumber', 'email', 'address'],
    properties: {
      id: { type: 'integer', description: 'The auto-generated id for the patient.' },
      zipCodeId: { type: 'integer', description: 'The zip code id for the patient.' },
      firstname: { type: 'string', description: "Patient's firstname." },
      lastname: { type: 'string', description: "Patient's lastname." },
      birthdate: { type: 'string', format: 'date-time', description: "Patient's birthdate." },
      socialSecurityNumber: { type: 'string', description: "Patient's social security number." },
      phoneNumber: { type: 'string', description: "Patient's phone number." },
      email: { type: 'string', description: "Patient's email." },
      address: { type: 'string', description: "Patient's address." },
      createdAt: {
        type: 'string',
        format: 'date-time',
        description: 'Date of creation.',
      },
      updatedAt: {
        type: 'string',
        format: 'date-time',
        description: 'Date of last update.',
      },
      channels: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'integer', description: 'The auto-generated id for the channel.' },
            patientId: { type: 'integer', description: 'The id of the patient associated with the channel.' },
            channelTypeId: { type: 'integer', description: 'The id of the channel type.' },
            channelType: {
              type: 'object',
              properties: {
                id: { type: 'integer', description: 'The auto-generated id for the channel type.' },
                name: { type: 'string', description: 'The name of the channel type.' },
                color: { type: 'string', description: 'The color associated with the channel type.' },
                order: { type: 'integer', description: 'The order of the channel type.' },
              },
            },
            lastMessage: {
              type: 'object',
              properties: {
                id: { type: 'string', description: 'The auto-generated id for the last message.' },
                channelId: { type: 'integer', description: 'The id of the channel associated with the last message.' },
                content: { type: 'string', description: 'The content of the last message.' },
                authorId: { type: 'integer', description: 'The id of the author of the last message.' },
              },
            },
            unreadMessagesCount: { type: 'integer', description: 'The number of unread messages in the channel.' },
            totalMessages: { type: 'integer', description: 'The total number of messages in the channel.' },
          },
        },
      },
    },
    example: {
      id: 1,
      zipCodeId: 691,
      firstname: 'Capitaine',
      lastname: 'Haddock',
      birthdate: '1980-01-01T00:00:00.000Z',
      socialSecurityNumber: '123456789012345',
      phoneNumber: '0123456789',
      email: 'capitaine@haddock.fr',
      address: '123 rue du port',
      createdAt: '2024-04-09T09:28:59.954Z',
      updatedAt: '2024-04-09T09:28:59.954Z',
      channels: [
        {
          id: 1,
          patientId: 1,
          channelTypeId: 1,
          channelType: {
            id: 1,
            name: 'Pharmacy',
            color: '#a742f5',
            order: 1,
          },
          lastMessage: {
            id: '6617f2998d0f328652b28991',
            channelId: 1,
            content: 'Test de bob',
            authorId: 2,
          },
          unreadMessagesCount: 2,
          totalMessages: 3,
        },
        {
          id: 2,
          patientId: 1,
          channelTypeId: 2,
          channelType: {
            id: 2,
            name: 'General',
            color: '#f54242',
            order: 2,
          },
          lastMessage: {
            id: '6617f2a28d0f328652b28993',
            channelId: 2,
            content: 'Nouveau tes tde bob',
            authorId: 2,
          },
          unreadMessagesCount: 1,
          totalMessages: 2,
        },
      ],
    },
  },
};
